version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      # Use Indian Standard Time (UTC +05:30)
      timezone: "Asia/Kolkata"
      time: "09:00"
    versioning-strategy: auto
